#!/usr/bin/env php
<?php
/*
 *
 *  Will watch files for you and run tasks when the file changes
 *  Once a file is updated the script will include your given file.
 *
 *  @author Matti van de Weem<mvdweem@gmail.com>
 *
 */

//Time between loops in ms
$sleep 	= 500;

// constants
$running = true;
$version = array();
$versionCurrent = array();

$tasks = json_decode(file_get_contents('tasks.json'));
foreach($tasks as $key => $t):
	$version[$key] = '';
	$versionCurrent[$key] = '';
	if(isset($t->onLaunch) && $t->onLaunch != ''):
		$toInc = 'tasks/'.$t->onLaunch.'.php';
		if(file_exists($toInc)):
			include($toInc);
		else:
			echo ('task executable for: '.$key.' not found..'."\n");
		endif;
	endif;
endforeach;
while($running):
	foreach($tasks as $key => $t):
		if(isset($t->watch) && $t->watch != ''):
			// shell_exec the the version file(this will reset file times and make it able to load)
			$versionCurrent[$key] = shell_exec('php includes/version.php '.$t->watch);
			if($version[$key] === $versionCurrent[$key] ):
				if(isset($t->onNoUpdate) && $t->onNoUpdate != ''):
					$toInc = 'tasks/'.$t->onNoUpdate.'.php';
					if(file_exists($toInc)):
						include($toInc);
					else:
						echo ('task executable for: '.$key.' not found..'."\n");
					endif;
				endif;
			else:
				$version[$key] = $versionCurrent[$key];
				if(isset($t->onUpdate) && $t->onUpdate != ''):
					$toInc = 'tasks/'.$t->onUpdate.'.php';
					if(file_exists($toInc)):
						include($toInc);
					else:
						echo ('task executable for: '.$key.' not found..'."\n");
					endif;
				endif;
			endif;
		endif;
	endforeach;
	sleep($sleep/1000);
endwhile;
exit;